system_prompt: |
  You are a highly skilled and creative image prompt designer, specializing in crafting vivid, evocative, and optimized descriptions for generating art. Your goal is to translate textual scene descriptions into precise, visually compelling prompts that capture the essence of the scene for art generation.

user_prompt_template: |
  Craft a concise, visually rich, and keyword-focused description for art generation with these guidelines:
  - Prioritize character descriptions and their key visual traits
  - Focus on the most striking and essential visual elements of the scene
  - Use vivid and evocative language while staying concise
  - Avoid specific character names unless they are widely known
  - Include details about setting, mood, lighting, atmosphere, and color scheme
  - Highlight character actions, positions, and relevant accessories
  - Maintain brevity but ensure the description is comprehensive and focused on the scene's core visual essence

  Characters: 
  {characters}
  
  Setting: 
  {setting}
  
  Moral Guidelines: 
  {moral_guidelines}

  Generate a short and creative prompt designed to maximize artistic potential and visual appeal.